# -*- coding: utf-8 -*-
"""PROJECT NO : 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgnyZNji9mgrKKE6v_XgtyE7lc5wss9E
"""

import numpy as np
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/SALES DATA.csv")
print("Dataset Loaded Successfully")
print(data.head())

product_category = data["Product_Category"].values
quantity = data["Quantity_Sold"].values
unit_price = data["Unit_Price"].values
sales_amount = data["Sales_Amount"].values
unit_cost = data["Unit_Cost"].values
discount = data["Discount"].values
print(product_category[:5])
print(quantity[:5])
print(unit_price[:5])
print(sales_amount[:5])

total_revenue = np.sum(sales_amount)
average_sales = np.mean(sales_amount)

print("Total Revenue:", total_revenue)
print("Average Sales:", average_sales)

print("First 10 Sales Records:", sales_amount[:10])
print("Last 5 Quantity Sold:", quantity[-5:])

mean_sales = np.mean(sales_amount)
median_sales = np.median(sales_amount)
variance_sales = np.var(sales_amount)
std_sales = np.std(sales_amount)

print("Mean Sales:", mean_sales)
print("Median Sales:", median_sales)
print("Variance:", variance_sales)
print("Standard Deviation:", std_sales)

calculated_revenue = quantity * unit_price
print("Calculated Revenue (First 10):", calculated_revenue[:10])

profit = (unit_price - unit_cost) * quantity
profit_percentage = (profit / sales_amount) * 100

print("Profit (First 10):", profit[:10])
print("Profit % (First 10):", profit_percentage[:10])

unique_categories = np.unique(product_category)

for category in unique_categories:
    category_sales = sales_amount[product_category == category]
    print(category, "- Total Sales:", np.sum(category_sales))

print("Highest Sale:", np.max(sales_amount))
print("Lowest Sale:", np.min(sales_amount))